version: '3'
services:

  weewx-core:
    container_name: weewx-core
    image: weewx
    #mac_address: d0:ca:ab:cd:ca:ca
    #cap_add:
    #  - NET_ADMIN
    #networks:
    #  pihole_pihole_network:
    #    ipv4_address: 192.168.X.X
    ports:
      - "8090:8090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/administrator/mounts/weewx/config/weewx.conf:/home/weewx/weewx.conf
      - /home/administrator/mounts/weewx/html/:/home/weewx/public_html/
      - /home/administrator/mounts/weewx/archive/:/home/weewx/archive/
    restart: unless-stopped

  weewx-web:
    container_name: weewx-web
    image: nginx:alpine
    #depends_on:
    #  - weewx-core
    #cap_add:
    #  - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/administrator/mounts/weewx/html/:/usr/share/nginx
      #- ${PWD}/src/default:/etc/nginx/conf.d/default.conf
      - /home/administrator/mounts/weewx/default:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - "8080:8080"

#networks:
#  pihole_pihole_network:
#    external: true
